#!/usr/bin/env python3
"""Custom check generated by prec."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path


def check(filenames: Sequence[Path]) -> int:
    """Require every non-empty file to end with exactly one newline."""
    failed = False
    for filename in filenames:
        try:
            content = filename.read_bytes()
        except OSError as error:
            print(f"{filename}: could not read file: {error}")
            failed = True
            continue

        if not content:
            continue
        trailing_newlines = content[len(content.rstrip(b"\r\n")) :]
        if not trailing_newlines:
            print(f"{filename}: must end with a newline")
            failed = True
        elif trailing_newlines not in {b"\n", b"\r\n"}:
            print(f"{filename}: must end with exactly one newline")
            failed = True
    return int(failed)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("filenames", nargs="*", type=Path)
    args = parser.parse_args(argv)
    return check(args.filenames)


if __name__ == "__main__":
    raise SystemExit(main())
