"""Create repository-local custom checks."""

import argparse
import json
import os
import re
import stat
import tempfile
from pathlib import Path

from prec.config.config import CONFIG_PATH, loads_config, valid_check_id
from prec.custom import custom_script_path
from prec.errors.errors import ConfigError, UsageError
from prec.git.patterns import PatternError, validate_pattern
from prec.git.repository import Repository

_PYTHON_TEMPLATE = '''#!/usr/bin/env python3
"""Custom check generated by prec."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path


def check(filenames: Sequence[Path]) -> int:
    """Return zero when the check passes and nonzero when it fails."""
    # Implement the check here.
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("filenames", nargs="*", type=Path)
    args = parser.parse_args(argv)
    return check(args.filenames)


if __name__ == "__main__":
    raise SystemExit(main())
'''

_BASH_TEMPLATE = """#!/usr/bin/env bash

check() {
    local -a filenames=("$@")
    # Implement the check here. The filenames are available as "${filenames[@]}".
    return 0
}

if [[ "${1-}" == "--" ]]; then
    shift
fi
check "$@"
"""


def configure_parser(parser: argparse.ArgumentParser) -> None:
    """Configure custom-check management commands."""
    commands = parser.add_subparsers(dest="check_command", required=True)
    add_parser = commands.add_parser("add", help="create and register a custom check")
    add_parser.add_argument("check_id", metavar="ID")
    add_parser.add_argument(
        "--language",
        choices=("python", "bash"),
        default="python",
        help="language for the generated check (default: python)",
    )
    add_parser.add_argument(
        "--files",
        action="append",
        default=[],
        metavar="PATTERN",
        help="Git-wildmatch include pattern; may be repeated",
    )


def _config_with_check(content: bytes | None, check_id: str, files: list[str]) -> bytes:
    if content is None:
        content = b"version = 1\n"
        config_has_checks = False
    else:
        config = loads_config(content)
        if any(check.id == check_id for check in config.checks):
            raise UsageError(f"check id `{check_id}` is already configured")
        config_has_checks = bool(config.checks)

    if not config_has_checks and b"checks" in content:
        content, substitutions = re.subn(
            rb"(?m)^[ \t]*checks[ \t]*=[ \t]*\[[ \t]*\][ \t]*(?:#.*)?(?:\r?\n|$)",
            b"",
            content,
            count=1,
        )
        if substitutions != 1:
            raise ConfigError(
                f"{CONFIG_PATH}: an empty `checks` array must be written as `checks = []` "
                "before a check can be added"
            )

    separator = b"" if content.endswith(b"\n\n") else b"\n" if content.endswith(b"\n") else b"\n\n"
    registration = [f"[[checks]]\nid = {json.dumps(check_id)}\n"]
    if files:
        patterns = ", ".join(json.dumps(pattern) for pattern in files)
        registration.append(f"files = [{patterns}]\n")
    return content + separator + "".join(registration).encode()


def _replace_file(path: Path, content: bytes, mode: int | None = None) -> None:
    temporary: Path | None = None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, name = tempfile.mkstemp(prefix=f".{path.name}.prec-", dir=path.parent)
        temporary = Path(name)
        with os.fdopen(descriptor, "wb") as file:
            file.write(content)
        if mode is not None:
            temporary.chmod(mode)
        temporary.replace(path)
    except OSError as error:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise ConfigError(f"could not write {path}: {error}") from error


def add_check(repository: Repository, args: argparse.Namespace) -> int:
    """Scaffold a custom check and register it in the configuration."""
    check_id: str = args.check_id
    files: list[str] = args.files
    if not valid_check_id(check_id):
        raise UsageError("check id must match ^[a-z][a-z0-9_-]*$ and be at most 64 characters")
    for pattern in files:
        try:
            validate_pattern(pattern)
        except PatternError as error:
            raise UsageError(f"invalid --files pattern: {error}") from error

    template = _PYTHON_TEMPLATE if args.language == "python" else _BASH_TEMPLATE
    relative_script = custom_script_path(check_id, args.language)
    script_path = repository.root / relative_script
    config_path = repository.root / CONFIG_PATH

    if script_path.exists() or script_path.is_symlink():
        raise UsageError(f"custom check path already exists: {relative_script}")
    if config_path.is_symlink():
        raise ConfigError(f"{CONFIG_PATH}: configuration must not be a symbolic link")
    try:
        config_content = config_path.read_bytes()
        config_mode = stat.S_IMODE(config_path.stat().st_mode)
    except FileNotFoundError:
        config_content = None
        config_mode = 0o644
    except OSError as error:
        raise ConfigError(f"{CONFIG_PATH}: cannot read configuration: {error}") from error

    updated_config = _config_with_check(config_content, check_id, files)
    _replace_file(script_path, template.encode(), mode=0o755)
    try:
        _replace_file(config_path, updated_config, mode=config_mode)
    except ConfigError:
        script_path.unlink(missing_ok=True)
        raise

    print(f"Created {relative_script}")
    print(f"Registered `{check_id}` in {CONFIG_PATH}")
    print("Stage both files before using `prec run --staged`.")
    return 0


def manage_checks(repository: Repository, args: argparse.Namespace) -> int:
    """Dispatch a custom-check management command."""
    if args.check_command == "add":
        return add_check(repository, args)
    raise UsageError(f"unknown check command: {args.check_command}")
