"""Install and uninstall Git hooks managed by prec."""

import argparse
import os
import shlex
import sys
import tempfile
from pathlib import Path

from prec.errors import HookError, RepositoryError
from prec.git.repository import Repository

_MARKER = b"# prec-managed-hook:v1\n"
_HEADER_PREFIX = b"#!/bin/sh\n# Generated by prec. Do not edit.\n"
_HEADER = _HEADER_PREFIX + _MARKER
_LEGACY_HEADER = _HEADER_PREFIX + b"# prec-managed-hook\n"


def configure_parser(parser: argparse.ArgumentParser) -> None:
    """Configure arguments accepted by the hook management commands."""


def _hook_path(repository: Repository) -> Path:
    raw_path = repository.git(
        ["rev-parse", "--path-format=absolute", "--git-path", "hooks/pre-commit"]
    )
    if raw_path.endswith(b"\n"):
        raw_path = raw_path[:-1]
    try:
        return Path(raw_path.decode("utf-8"))
    except UnicodeDecodeError as error:
        raise RepositoryError("Git hook path is not valid UTF-8") from error


def _script() -> bytes:
    arguments = "run --staged"
    python = shlex.quote(sys.executable)
    return (
        f"{_HEADER.decode()}"
        f"INSTALL_PYTHON={python}\n"
        'if [ -x "$INSTALL_PYTHON" ]; then\n'
        f'    exec "$INSTALL_PYTHON" -m prec {arguments}\n'
        "elif command -v prec >/dev/null 2>&1; then\n"
        f"    exec prec {arguments}\n"
        "else\n"
        "    echo 'prec: error: executable not found; reinstall the hook' >&2\n"
        "    exit 2\n"
        "fi\n"
    ).encode()


def _is_managed(content: bytes) -> bool:
    return content.startswith((_HEADER, _LEGACY_HEADER))


def _read_existing(path: Path) -> bytes | None:
    if path.is_symlink():
        raise HookError(f"refusing to replace symbolic link: {path}")
    if not path.exists():
        return None
    if not path.is_file():
        raise HookError(f"Git hook path is not a regular file: {path}")
    try:
        return path.read_bytes()
    except OSError as error:
        raise HookError(f"could not read Git hook {path}: {error}") from error


def install(repository: Repository, args: argparse.Namespace) -> int:
    """Install the pre-commit hook."""
    del args
    path = _hook_path(repository)
    existing = _read_existing(path)
    if existing is not None and not _is_managed(existing):
        raise HookError(f"Git hook already exists and is not managed by prec: {path}")

    temporary: Path | None = None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.prec-", dir=path.parent)
        temporary = Path(temporary_name)
        with os.fdopen(descriptor, "wb") as file:
            file.write(_script())
        temporary.chmod(0o755)
        temporary.replace(path)
    except OSError as error:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise HookError(f"could not install Git hook {path}: {error}") from error

    print(f"prec installed at {path}")
    return 0


def uninstall(repository: Repository, args: argparse.Namespace) -> int:
    """Uninstall the pre-commit hook if it is managed by prec."""
    del args
    path = _hook_path(repository)
    existing = _read_existing(path)
    if existing is None:
        print(f"prec hook is not installed at {path}")
        return 0
    if not _is_managed(existing):
        raise HookError(f"Git hook is not managed by prec; refusing to remove it: {path}")
    try:
        path.unlink()
    except OSError as error:
        raise HookError(f"could not uninstall Git hook {path}: {error}") from error
    print(f"prec uninstalled from {path}")
    return 0
